on:
  push:
    branches: [main]
  workflow_dispatch:

name: pkgdown-main

jobs:
  pkgdown-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Generate sample reports
        shell: Rscript {0}
        run: |
          devtools::load_all()
          dir.create(here::here("pkgdown", "assets"), recursive = TRUE)

          lCharts <- MakeCharts(
            dfResults = gsm.core::reportingResults,
            dfGroups = gsm.core::reportingGroups,
            dfMetrics = gsm.core::reportingMetrics,
            dfBounds = gsm.core::reportingBounds
          )

          Report_KRI(
            lCharts = lCharts,
            dfResults =  FilterByLatestSnapshotDate(gsm.core::reportingResults),
            dfGroups =  gsm.core::reportingGroups,
            dfMetrics = gsm.core::reportingMetrics,
            strOutputDir = here::here("pkgdown", "assets"),
            strOutputFile = "report_kri_site.html"
          )

          ## Country Report
            lCharts_country <- MakeCharts(
            dfResults = gsm.core::reportingResults_country,
            dfGroups = gsm.core::reportingGroups_country,
            dfMetrics = gsm.core::reportingMetrics_country,
            dfBounds = gsm.core::reportingBounds_country
          )

          Report_KRI(
            lCharts = lCharts_country,
            dfResults =  FilterByLatestSnapshotDate(gsm.core::reportingResults_country),
            dfGroups =  gsm.core::reportingGroups_country,
            dfMetrics = gsm.core::reportingMetrics_country,
            strOutputDir = here::here("pkgdown", "assets"),
            strOutputFile = "report_kri_country.html"
          )


      - name: Deploy pkgdown
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
