on:
  repository_dispatch:
    types: [qualification]

name: qualification-report

jobs:
  qualification-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, github::${{ github.event.client_payload.repository }}@${{ github.event.client_payload.head_ref }}
          needs: check, qualification

      - name: build vignette
        run: |
          install.packages("devtools")
          devtools::install(dependencies = T)
          tools::buildVignette("./vignettes/Qualification.Rmd")
        shell: Rscript {0}

      # Upload the qulafication report to the release
      - name: Upload report to release
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./Qualification.pdf
          asset_name: qualification-report.pdf
          repo_name: ${{ github.event.client_payload.repository }}
          repo_token: ${{ github.event.client_payload.GH_TOKEN }}
          tag: ${{ github.event.client_payload.release_tag }}
          overwrite: true
